questions = [ ("Does morality exist?", ["Yes, it’s subjective", "Yes, it’s objective", "No"]),
              ("Do you like candy?", [ "Love it!", "Kind of", "sure?", "no"]),
              ("Is there meaning in life?", ["yes", "no", "Doesn’t Matter"]),
              ("Does God exist?", ["Yes", "No", "Unknowable", "Doesn’t Matter"]),
              ("Do you have a purpose?", ["Yes", "No", "Unsure", "Doesn’t Matter"]),
              ("Are humans inherently…", ["Good", "Evil", "Both", "Neither"]),
              ("How did the universe begin?", ["Random Chance", "Uncreated Creator", "Necessarily", "The universe doesn’t have a beginning"]),
              ("Is there life after death?", ["Yes", "No", "Unknowable", "Doesn’t matter"]),
              ("Are you going to the Veritas Forum?", ["Of course", "No doubt", "Yes", "You betcha"]),
              ("Are we in the Matrix?", ["Yes", "No", "Red pill", "Blue pill"]),
              ("Does goodness exist?", ["Yes, and it’s objective", "Yes, but it’s subjective", "Doesn’t exist", "Doesn’t Matter"]),
              ("Does truth exist?", ["Yes, and it’s objective", "Yes, but it’s subjective", "Doesn’t exist", "Doesn’t matter"]),
              ("Where does your purpose come from?", ["Myself", "God", "Other people", "Nature"]),
              ("What’s your default answer on scantrons?", ["A", "B", "C", "D"]),
              ("Are human beings special?", ["Yes", "No", "Doesn’t matter"]),
              ("Does happiness matter?", ["Yes", "No"]),
              ("Are you satisfied with your life?", ["Yes", "Kind of", "Not really", "Not at all"]),
              ("Favorite place to eat on campus?", ["The Ave", "805 kitchen", "Yo Crea", "Mustang Station"]),
              ("Do you have a soul?", ["Yes", "No", "Not sure", "Unknowable"]),
              ("Can a world exist without evil?", ["Yes", "No", "Evil doesn’t exist", "Unknowable"]),
              ("Does everything have an opposite?", ["Yes", "No", "Not sure"]),
              ("Are the brain and the mind synonymous?", ["Yes", "No", "Unkowable", "Doesn’t matter"]) ]
    
